<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>PNG2JPEG</RootNamespace>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Models\" />
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.3" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
		<PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.17.2" />
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Magick.NET.AvaloniaMediaImaging" Version="1.1.16" />
	</ItemGroup>
</Project>
